// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	amqp091 "github.com/rabbitmq/amqp091-go"
	mock "github.com/stretchr/testify/mock"

	slog "log/slog"
)

// ChannelProvider is an autogenerated mock type for the channelProvider type
type ChannelProvider struct {
	mock.Mock
}

type ChannelProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *ChannelProvider) EXPECT() *ChannelProvider_Expecter {
	return &ChannelProvider_Expecter{mock: &_m.Mock}
}

// Channel provides a mock function with no fields
func (_m *ChannelProvider) Channel() (*amqp091.Channel, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Channel")
	}

	var r0 *amqp091.Channel
	var r1 error
	if rf, ok := ret.Get(0).(func() (*amqp091.Channel, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *amqp091.Channel); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*amqp091.Channel)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChannelProvider_Channel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Channel'
type ChannelProvider_Channel_Call struct {
	*mock.Call
}

// Channel is a helper method to define mock.On call
func (_e *ChannelProvider_Expecter) Channel() *ChannelProvider_Channel_Call {
	return &ChannelProvider_Channel_Call{Call: _e.mock.On("Channel")}
}

func (_c *ChannelProvider_Channel_Call) Run(run func()) *ChannelProvider_Channel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ChannelProvider_Channel_Call) Return(_a0 *amqp091.Channel, _a1 error) *ChannelProvider_Channel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChannelProvider_Channel_Call) RunAndReturn(run func() (*amqp091.Channel, error)) *ChannelProvider_Channel_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function with no fields
func (_m *ChannelProvider) Logger() *slog.Logger {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *slog.Logger
	if rf, ok := ret.Get(0).(func() *slog.Logger); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slog.Logger)
		}
	}

	return r0
}

// ChannelProvider_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type ChannelProvider_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *ChannelProvider_Expecter) Logger() *ChannelProvider_Logger_Call {
	return &ChannelProvider_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *ChannelProvider_Logger_Call) Run(run func()) *ChannelProvider_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ChannelProvider_Logger_Call) Return(_a0 *slog.Logger) *ChannelProvider_Logger_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelProvider_Logger_Call) RunAndReturn(run func() *slog.Logger) *ChannelProvider_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// NewChannelProvider creates a new instance of ChannelProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChannelProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChannelProvider {
	mock := &ChannelProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
