// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	amqp091 "github.com/rabbitmq/amqp091-go"
	mock "github.com/stretchr/testify/mock"
)

// Dialer is an autogenerated mock type for the dialer type
type Dialer struct {
	mock.Mock
}

type Dialer_Expecter struct {
	mock *mock.Mock
}

func (_m *Dialer) EXPECT() *Dialer_Expecter {
	return &Dialer_Expecter{mock: &_m.Mock}
}

// Channel provides a mock function with no fields
func (_m *Dialer) Channel() (*amqp091.Channel, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Channel")
	}

	var r0 *amqp091.Channel
	var r1 error
	if rf, ok := ret.Get(0).(func() (*amqp091.Channel, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *amqp091.Channel); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*amqp091.Channel)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Dialer_Channel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Channel'
type Dialer_Channel_Call struct {
	*mock.Call
}

// Channel is a helper method to define mock.On call
func (_e *Dialer_Expecter) Channel() *Dialer_Channel_Call {
	return &Dialer_Channel_Call{Call: _e.mock.On("Channel")}
}

func (_c *Dialer_Channel_Call) Run(run func()) *Dialer_Channel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Dialer_Channel_Call) Return(_a0 *amqp091.Channel, _a1 error) *Dialer_Channel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Dialer_Channel_Call) RunAndReturn(run func() (*amqp091.Channel, error)) *Dialer_Channel_Call {
	_c.Call.Return(run)
	return _c
}

// Connect provides a mock function with no fields
func (_m *Dialer) Connect() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Dialer_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type Dialer_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
func (_e *Dialer_Expecter) Connect() *Dialer_Connect_Call {
	return &Dialer_Connect_Call{Call: _e.mock.On("Connect")}
}

func (_c *Dialer_Connect_Call) Run(run func()) *Dialer_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Dialer_Connect_Call) Return(_a0 error) *Dialer_Connect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Dialer_Connect_Call) RunAndReturn(run func() error) *Dialer_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// NewDialer creates a new instance of Dialer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDialer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Dialer {
	mock := &Dialer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
