version: '3'

tasks:
  mailpit/start:
    desc: "Start Mailpit SMTP server for local development"
    summary: |
      Start Mailpit container for capturing emails during development.
      Web UI available at http://localhost:8025
    cmds:
      - docker run -d --name mailpit_adapter -p 1025:1025 -p 8025:8025 axllent/mailpit:latest
    # секция status определяет, нужно ли выполнять задачу
    status:
      - docker ps --filter "name=mailpit_adapter" --format "{{.Names}}" | grep -q mailpit_adapter

  mailpit/stop:
    desc: "Stop Mailpit container"
    summary: |
      Stop and remove Mailpit container.
    cmds:
      - docker rm -f mailpit_adapter || true

  mailpit/restart:
    desc: "Restart Mailpit container"
    cmds:
      - task: mail/mailpit/stop
      - task: mail/mailpit/start

  mailpit/logs:
    desc: "View Mailpit logs"
    summary: |
      Show Mailpit container logs.
    cmds:
      - docker logs -f mailpit_adapter

  mailpit/test:
    desc: "Test SMTP connection to Mailpit"
    summary: |
      Verify Mailpit is accepting connections.
    cmds:
      - nc -z localhost 1025 && echo "SMTP port 1025 is open" || echo "SMTP port 1025 is not open"
